# .github/workflows/daily-fetch-and-post.yml
name: Daily Fetch and Post

# Runs every day at 10:00 Moscow Time (MSK = UTC+3 → 07:00 UTC)
on:
    schedule:
      - cron: '0 7 * * *'  # Запуск каждый день в 7:00
    workflow_dispatch:       # Ручной запуск

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install --upgrade pip
            pip install -r requirements.txt
          fi

      - name: Run fetch-and-post script
        run: python test_fetch_and_post.py