# .github/workflows/daily_fetch_and_update.yml
# Автоматический запуск скрипта для обновления NHL Standings и Injuries

name: Daily NHL Data Fetch and Update

on:
  schedule:
    # запуск каждый день в 7:00 UTC
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run NHL data fetch script
        run: |
          python test_fetch_and_post.py

      - name: Configure Git for commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push updated HTML
        run: |
          git add output/nhl_standings.html output/nhl_injuries.html
          if git diff --cached --quiet; then
            echo "🔄 No changes to commit"
          else
            git commit -m "chore: auto-update NHL output files"
            git push
          fi
